#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Logs from the minecraft unit and prometheus units
[sources.journalctl_in]
type = "journald"
include_units = [ "minecraft", "minecraft_exporter", "node_exporter" ]

# Minecraft server metrics
[sources.minecraft_exporter]
type = "prometheus_scrape"
endpoints = [ "http://localhost:9150/metrics" ]
scrape_interval_secs = 15

# Host VM metrics
[sources.host]
type = "host_metrics"
collectors = [ "cpu", "disk", "load", "host", "memory", "network" ]
scrape_interval_secs = 15

# Loki sink
[sinks.loki]
type = "loki"
inputs = [ "journalctl_in" ]
endpoint = "https://logs-prod-us-central1.grafana.net/loki/api/v1/push"
auth.strategy = "basic"
auth.user = "${LOKI_USERNAME}"
auth.password = "${LOKI_PASSWORD}"

[sinks.prom]
type = "prometheus_remote_write"
inputs = [ "minecraft_exporter", "host" ]
endpoint = "https://prometheus-us-central1.grafana.net/api/prom/push"
auth.strategy = "basic"
auth.user = "${PROM_USERNAME}"
auth.password = "${PROM_PASSWORD}"